# Generated by Django 5.2.6 on 2025-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cart-wise", "cart-wise"),
                            ("product-wise", "product-wise"),
                            ("bxgy", "bxgy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField()),
                ("conditions", models.JSONField()),
            ],
        ),
    ]
