# Generated by Django 5.2.6 on 2025-10-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="conditions",
        ),
    ]
