# Generated by Django 5.2.6 on 2025-10-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_remove_coupon_conditions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="type",
            new_name="coupon_type",
        ),
    ]
