# Generated by Django 5.2.6 on 2025-11-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_rename_type_coupon_coupon_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="coupon_type",
            new_name="type",
        ),
    ]
