# Generated by Django 5.2.6 on 2025-11-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="cart_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_id",
            new_name="id",
        ),
    ]
