# Generated by Django 5.2.6 on 2025-11-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_cart_id_cart_id_rename_product_id_product_id"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
